from pydantic import BaseModel, Field


class CommunityScoreDTO(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommunityScoreDTO - a model defined in OpenAPI

        community_id: The community_id of this CommunityScoreDTO [Optional].
        value: The value of this CommunityScoreDTO [Optional].
    """

    community_id: int = Field(alias="community_id", default=None)
    value: int = Field(alias="value", default=None)


class UserScoreDTO(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    UserScoreDTO - a model defined in OpenAPI

        user_id: The user_id of this UserScoreDTO [Optional].
        value: The value of this UserScoreDTO [Optional].
    """

    user_id: int = Field(alias="user_id", default=None)
    value: int = Field(alias="value", default=None)
