openapi: 3.0.0
x-stoplight:
  id: 7rje00rjblxsg
info:
  title: openapi_occupancy
  version: '1.0'
  description: Occupany endpoints
  contact:
    name: Roma
    email: ecoapptracker@gmail.com
servers:
  - url: 'http://127.0.0.1:8000'
paths:
  '/occupancy/get/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: occupancy id
    get:
      summary: Get occupancy category
      tags:
        - Occupancy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OccupancyCategorySchema'
        '403':
          description: User is not active
      operationId: get-occupancy-get-id
      description: Get occupancy
  /occupancy/list:
    get:
      summary: List occupancy category
      tags:
        - Occupancy
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/OccupancyCategorySchema'
        '403':
          description: User is not active
      operationId: get-occupancy-list
      description: Get list occupancy category
components:
  schemas:
    OccupancyCategorySchema:
      title: OccupancyCategorySchema
      x-stoplight:
        id: zhlqn6iqme6gj
      type: object
      description: |
        Occupancy category schema
      properties:
        id:
          type: integer
          x-stoplight:
            id: 1iq3332zzpo0b
          description: |
            Occupancy id
        name:
          type: string
          x-stoplight:
            id: 0mcyzindrpmhg
        language:
          type: string
          x-stoplight:
            id: rjes94mmzdqp8
tags:
  - name: Occupancy
    description: Occupancy endpoints
