"""Database init tables v1

Revision ID: 96044a614262
Revises: 0677b5fb696a
Create Date: 2023-04-29 02:40:05.577929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96044a614262'
down_revision = '0677b5fb696a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'community', ['name'])
    op.create_unique_constraint(None, 'user', ['username'])
    op.create_unique_constraint(None, 'value_type', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'value_type', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'community', type_='unique')
    # ### end Alembic commands ###
