from datetime import datetime

from pydantic import BaseModel, Field

from src.core.enum.challenges.status import OccupancyStatusEnum


class MissionGroupCreateObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MissionGroupCreateDTO - a model defined in OpenAPI

        mission_id: The mission_id of this MissionGroupCreateDTO .
        author: The author of this MissionGroupCreateDTO .
        place: The place of this MissionGroupCreateDTO .
        meeting_date: The meeting_date of this MissionGroupCreateDTO .
        people_required: The people_required of this MissionGroupCreateDTO .
        people_max: The people_max of this MissionGroupCreateDTO .
        comment: The comment of this MissionGroupCreateDTO .
        status: The status of this MissionGroupCreateDTO .
    """

    mission_id: int = Field(alias="mission_id", default=None)
    author: str = Field(alias="author", default=None)
    place: str = Field(alias="place", default=None)
    meeting_date: datetime = Field(alias="meeting_date", default=None)
    people_required: int = Field(alias="people_required", default=None)
    people_max: int = Field(alias="people_max", default=None)
    comment: str = Field(alias="comment", default=None)
    status: OccupancyStatusEnum = Field(alias="status", default=OccupancyStatusEnum.ACTIVE)


class MissionGroupEntity(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MissionGroupEntity - a model defined in OpenAPI

        id: The id of this MissionGroupEntity .
        group_id: The group_id of this MissionGroupEntity .
        mission_id: The mission_id of this MissionGroupEntity .
        author: The author of this MissionGroupEntity .
        date_start: The date_start of this MissionGroupEntity .
        date_close: The date_close of this MissionGroupEntity .
        status: The status of this MissionGroupEntity .
        place: The place of this MissionGroupEntity .
        meeting_date: The meeting_date of this MissionGroupEntity .
        people_required: The people_required of this MissionGroupEntity .
        people_max: The people_max of this MissionGroupEntity .
        comment: The comment of this MissionGroupEntity .
    """

    id: int = Field(alias="id", default=None)
    group_id: int = Field(alias="group_id", default=None)
    mission_id: int = Field(alias="mission_id", default=None)
    author: str = Field(alias="author", default=None)
    date_start: datetime = Field(alias="date_start", default=None)
    date_close: datetime = Field(alias="date_close", default=None)
    status: OccupancyStatusEnum = Field(alias="status", default=OccupancyStatusEnum.ACTIVE)
    place: str = Field(alias="place", default=None)
    meeting_date: datetime = Field(alias="meeting_date", default=None)
    people_required: int = Field(alias="people_required", default=None)
    people_max: int = Field(alias="people_max", default=None)
    comment: str = Field(alias="comment", default=None)


class MissionGroupFilterObject(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    MissionGroupFilter - a model defined in OpenAPI

        group_id: The group_id of this MissionGroupFilter .
        group_id_list: The group_id_list of this MissionGroupFilter .
        mission_id: The mission_id of this MissionGroupFilter .
        status: The status of this MissionGroupFilter .
    """

    group_id: int = Field(alias="group_id", default=None)
    group_id_list: list[int] = Field(alias="group_id_list", default=None)
    mission_id: int = Field(alias="mission_id", default=None)
    status: OccupancyStatusEnum = Field(alias="status", default=OccupancyStatusEnum.ACTIVE)


class MissionGroupUpdateObject(BaseModel):
    """
    MissionGroupUpdateDTO - a model defined in OpenAPI

        date_close: The date_close of this MissionGroupUpdateDTO .
        status: The status of this MissionGroupUpdateDTO .
        place: The place of this MissionGroupUpdateDTO .
        meeting_date: The meeting_date of this MissionGroupUpdateDTO .
        people_required: The people_required of this MissionGroupUpdateDTO .
        people_max: The people_max of this MissionGroupUpdateDTO .
        comment: The comment of this MissionGroupUpdateDTO .
    """

    date_close: datetime = Field(alias="date_close", default=None)
    status: OccupancyStatusEnum = Field(alias="status", default=OccupancyStatusEnum.ACTIVE)
    place: str = Field(alias="place", default=None)
    meeting_date: datetime = Field(alias="meeting_date", default=None)
    people_required: int = Field(alias="people_required", default=None)
    people_max: int = Field(alias="people_max", default=None)
    comment: str = Field(alias="comment", default=None)
