from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.group.privacy import GroupPrivacyEnum


class Group(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Group - a model defined in OpenAPI

        id: The id of this Group [Optional].
        name: The name of this Group.
        privacy: The privacy of this Group.
        description: The description of this Group [Optional].
    """

    id: int = Field(alias="id", default=None)
    name: str = Field(alias="name")
    privacy: GroupPrivacyEnum = Field(alias="privacy")
    description: str = Field(alias="description", default=None)


Group.update_forward_refs()
