from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class GroupInviteCode(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GroupInviteCode - a model defined in OpenAPI

        group_id: The group_id of this GroupInviteCode [Optional].
        code: The code of this GroupInviteCode [Optional].
        expire_time: The expire_time of this GroupInviteCode [Optional].
    """

    group_id: int = Field(alias="group_id", default=None)
    code: str = Field(alias="code", default=None)
    expire_time: datetime = Field(alias="expire_time", default=None)


GroupInviteCode.update_forward_refs()
