from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.group.role import GroupRoleEnum


class GroupRoleUpdate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GroupRoleUpdate - a model defined in OpenAPI

        role: The role of this GroupRoleUpdate [Optional].
    """

    role: GroupRoleEnum = Field(alias="role", default=None)


GroupRoleUpdate.update_forward_refs()
