from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.group.role import GroupRoleEnum


class GroupRole(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GroupRole - a model defined in OpenAPI

        user_id: The user_id of this GroupRole [Optional].
    """

    user_id: str = Field(alias="user_id", default=None)
    group_id: int = Field(alias="group_id", default=None)
    role: GroupRoleEnum = Field(alias="role", default=None)


GroupRole.update_forward_refs()
