from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.group.privacy import GroupPrivacyEnum


class GroupUpdate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    GroupUpdate - a model defined in OpenAPI

        name: The name of this GroupUpdate [Optional].
        privacy: The privacy of this GroupUpdate [Optional].
        description: The description of this GroupUpdate [Optional].
    """

    name: str | None = Field(alias="name", default=None)
    privacy: GroupPrivacyEnum | None = Field(alias="privacy", default=None)
    description: str | None = Field(alias="description", default=None)


GroupUpdate.update_forward_refs()
