from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.community.privacy import CommunityPrivacyEnum


class Community(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    Community - a model defined in OpenAPI

        id: The id of this Community [Optional].
        name: The name of this Community.
        privacy: The privacy of this Community.
        description: The description of this Community [Optional].
    """

    id: int = Field(alias="id", default=None)
    name: str = Field(alias="name")
    privacy: CommunityPrivacyEnum = Field(alias="privacy")
    description: str = Field(alias="description", default=None)


Community.update_forward_refs()
