from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.community.role import CommunityRoleEnum


class CommunityRoleUpdate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommunityRoleUpdate - a model defined in OpenAPI

        role: The role of this CommunityRoleUpdate [Optional].
    """

    role: CommunityRoleEnum = Field(alias="role", default=None)


CommunityRoleUpdate.update_forward_refs()
