from __future__ import annotations

from datetime import datetime

from pydantic import BaseModel, Field


class CommunityInviteCode(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommunityInviteCode - a model defined in OpenAPI

        community_id: The community_id of this CommunityInviteCode [Optional].
        code: The code of this CommunityInviteCode [Optional].
        expire_time: The expire_time of this CommunityInviteCode [Optional].
    """

    community_id: int = Field(alias="community_id", default=None)
    code: str = Field(alias="code", default=None)
    expire_time: datetime = Field(alias="expire_time", default=None)


CommunityInviteCode.update_forward_refs()
