from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.community.privacy import CommunityPrivacyEnum


class CommunityUpdate(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommunityUpdate - a model defined in OpenAPI

        name: The name of this CommunityUpdate [Optional].
        privacy: The privacy of this CommunityUpdate [Optional].
        description: The description of this CommunityUpdate [Optional].
    """

    name: str | None = Field(alias="name", default=None)
    privacy: CommunityPrivacyEnum | None = Field(alias="privacy", default=None)
    description: str | None = Field(alias="description", default=None)


CommunityUpdate.update_forward_refs()
