from __future__ import annotations

from pydantic import BaseModel, Field

from src.core.enum.community.role import CommunityRoleEnum


class CommunityRole(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    CommunityRole - a model defined in OpenAPI

        user_id: The user_id of this CommunityRole [Optional].
    """

    user_id: int = Field(alias="user_id", default=None)
    community_id: int = Field(alias="community_id", default=None)
    role: CommunityRoleEnum = Field(alias="role", default=None)


CommunityRole.update_forward_refs()
